baseURL: 'http://example.org/'
languageCode: 'en-us'
title: '"Und was machst du da?" PODCAST'
theme: 'papermod'

params:
    homeInfoParams:
      Title: Und was machst du da?
      Content: 
    socialIcons: # optional
      - name: "twitter"
        url: "www.twitter.com"
    defaultTheme: dark
    author:
      name: Patrice
      email: <email>
    twitter: "@falkoin" 

    mainSections:
      - blog
      - episodes # see https://gohugo.io/functions/where/#mainsections

    podcast:
      description: Cool Stuff
      tagline: Foodie Flashback - Food & Memories
      download_url: https://cdn.foodieflashback.com/episodes/
      cdn_url: https://cdn.foodieflashback.com/
      itunes_url: https://podcasts.apple.com/us/podcast/foodie-flashback/id1504783815
      itunes_id: id1504783815

menu:
    main:
        - name: Über
          url: ueber
          weight: 5
        - name: Impressum
          url: impressum
          weight: 5

## Podcast
outputFormats:
  mp3feed:
    MediaType: "application/rss+xml"
    BaseName: "index"
    path: "/feed/mp3"
    IsHTML: false
    IsPlainText: true
    noUgly: true
    Rel: "alternate"

outputs:
  home:
    - HTML
    - AMP
    - RSS
    - mp3feed
  